<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLerlv2x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLerlv2x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLerlv2x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLerlv2x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLerlv2x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Lerlv2x',
    'container.build_id' => '306b6093',
    'container.build_time' => 1547077338,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLerlv2x');
